# Generated by Django 6.1.1 on 2026-09-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup verification'), ('password_reset', 'Password reset')], default='signup', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_em_user_id_63c1d9_idx'),
        ),
    ]
